
services:
  python:
    build: .
    depends_on:
      - db


  db:
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: expense_controller
      MYSQL_ROOT_PASSWORD: Harlan27474129!\


    volumes:
    - datadir:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  datadir: null

